# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vier Legend
email: vierlegend@novastrike.com
description: > # this means to ignore newlines until "baseurl:"
  An awesome description here
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vierlegend.novastrike.com" # the base hostname & protocol for your site
twitter_username: vierlegend
github_username:  vier-legend

# Build settings
markdown: kramdown
